title:              Blog
tagline:            on GitHub Pages
description:        Blog of Martin Divis.
url:                http://chrlic.github.io

author:
  name:             Martin Divis
  email:            mdivis@cisco.com

google_analytics: G-YBV8T6MDDX
# GitHub Pages / Jekyll configuration
plugins: [jekyll-paginate]
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
